#!/bin/bash

exe="/usr/sbin/no-ip.sh"


start() {
	echo "Starting no-ip.sh"
	instance=$(pgrep -fl no-ip.s[h])
	if [ -n "$instance" ]
	then
		echo "Already running."
	else
		sh $exe > /dev/null 2>&1 &
	fi
}

stop() {
    echo "Shutting down no-ip.sh"
    kill -9 $(pgrep -f no-ip.s[h])
}

restart() {
    echo "Restarting no-ip.sh"
    stop
    sleep 2
    start
}

satus(){
	echo stat -c %y exe
}

case "$1" in
    start)
        start
    ;;
    stop)
        stop
    ;;
    restart)
        restart
    ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
    ;; esac

exit 0
